*FILES '$SR3FILE'
*SPREADSHEET
*PRECISION 4
*TIME ON
*TABLE-FOR *PARAMETERS 'Oil Rate SC - Monthly'
   *COLUMN-FOR *WELLS *ALL-PRODUCERS
*TABLE-END
*TABLE-FOR *PARAMETERS 'Water Rate SC - Monthly'
   *COLUMN-FOR *WELLS *ALL-PRODUCERS
*TABLE-END
*TABLE-FOR *PARAMETERS 'Water Rate SC - Monthly'
   *COLUMN-FOR *WELLS *ALL-INJECTORS
*TABLE-END
